### ISSUE TITLE
Please un-submodule  sound_api_core and add dependency instead

### ISSUE THREAD

**Issue by Bastrabun** [mt-mods/basic_materials#18]
At least - if possible. Is there a reason it was done this way?

It isn't really a bug, only "inconvenient" for my use case, I have basic_materials as a submoduled as well.

**Comment by wsor4035** [comment]
use submodule recursion - see https://github.com/mt-mods/basic_materials/issues/4 where this topic was already discussed.

**Comment by wsor4035** [comment]
https://github.com/mt-mods/basic_materials/commit/35b9cc4dde9d9a20fd1b066975536d5b62993a98
