### ISSUE TITLE
Silicon lump crafting recipe doesn't appear in recipe book

### ISSUE THREAD

**Issue by FlitPix** [mt-mods/basic_materials#23]
The recipe to craft silicon lumps does not appear in the recipe book. You can still craft silicon lumps despite this. This occurs both with and without `mesecons_materials` installed.

No other recipe has this issue.

**Comment by FlitPix** [comment]
Currently, we use `minetest.register_alias_force` with `mesecons_materials:silicon` to ensure that it uses the basic_materials texture. However, despite this, we still attempt to reference `mesecons_materials:silicon` here:

https://github.com/mt-mods/basic_materials/blob/1009295ee68c490e388302d0600f293685226b67/crafts.lua#L1-L17
https://github.com/mt-mods/basic_materials/blob/1009295ee68c490e388302d0600f293685226b67/crafts.lua#L528-L536

**Comment by wsor4035** [comment]
> Currently, we use `minetest.register_alias_force` with `mesecons_materials:silicon` to ensure that it uses the basic_materials texture

this is incorrect. it is forced aliased so that you dont have two duplicate items in game.
