### ISSUE TITLE
#8 issue with replacement crafts

### ISSUE THREAD

**Issue by wsor4035** [mt-mods/basic_materials#9]
what the title says, causes a crash. found when working on https://github.com/mt-mods/basic_materials/pull/8

**Comment by mazes-80** [comment]
Latest commit #8 also introduce a crash when no i3
ERROR[Main]: ModError: Failed to load and run script from .minetest/mods/basic_materials/init.lua:                      
ERROR[Main]: Invalid replacements (output="basic_materials:terracotta_base 8")                                                    
ERROR[Main]: stack traceback:                                                                                                     
ERROR[Main]:       [C]: in function 'register_craft'                                                                              
ERROR[Main]:       .minetest/mods/basic_materials/crafts.lua:283: in main chunk                                         
ERROR[Main]:       [C]: in function 'dofile'                                                                                      
ERROR[Main]:       .minetest/mods/basic_materials/init.lua:13: in main chunk

**Comment by mazes-80** [comment]
With unified_inventory when I look for recipe based on wet_cement: list is empty, despite recipe for concrete_block uses wet_cement.
I realized it just now
